### ISSUE TITLE
README中的入门部分关于--mode的参数的解释，中英文对应不上

### ISSUE THREAD

**Issue by joner11234** [emo-crab/observer_ward#315]
README中的入门部分关于--mode的参数的解释，中英文对应不上，使用的时候--mode danger 会提示错误，请问怎么能开启danger模式呢

**Comment by cn-kali-team** [comment]
目前还用不上这个参数，之前是想着加一个模式选择：http模式跑web指纹，tcp模式跑服务指纹，但是现在还没想到要不要加，所以文档没有写这个参数的用法

**Comment by joner11234** [comment]
现在是只会请求首页吗，我看指纹中有请求一些特别路径的指纹，怎么能开启请求特殊路径的模式呢

**Comment by joner11234** [comment]
师傅，我本地监听了一个http，使用nacos这个指纹进行识别，只收到了一个请求，没有指纹中的特殊路径的请求，

```python
python -m http.server 8999
Serving HTTP on :: port 8999 (http://[::]:8999/) ...
::ffff:127.0.0.1 - - [24/Jul/2024 17:15:13] "GET / HTTP/1.1" 200 -
```
observer_ward的版本是最新的
```
brew info observer_ward
==> observerward: stable 2024.7.23 (bottled)
```

使用的指纹识别命令
```shell
observer_ward -t http://127.0.0.1:8999  -p web-fingerprint/alibaba/nacos.yaml
```

Nacos的指纹
```yaml

id: alibaba-nacos
info:
  name: alibaba-nacos
  author: cn-kali-team
  tags: detect,tech,alibaba-nacos
  severity: info
  metadata:
    product: nacos
    vendor: alibaba
    verified: true
http:
- method: GET
  path:
  - '{{BaseURL}}/'
  - '{{BaseURL}}/nacos/'
  matchers:
  - type: word
    words:
    - <title>nacos</title>
    case-insensitive: true


```
