### ISSUE TITLE
v4版本似乎words逻辑更改了

### ISSUE THREAD

**Issue by pykiller** [emo-crab/observer_ward#333]
rt以前是and关系，写的指纹到v4版本发现变成or关系。怎么整老哥

**Comment by cn-kali-team** [comment]
文档有写
例如：tomcat的规则，多个关键词，必须全部同时匹配
```yaml
matchers:
  - type: word
    words:
      - /manager/html
      - /manager/status
    condition: and
```
