### ISSUE TITLE
编码问题

### ISSUE THREAD

**Issue by zowie218** [emo-crab/observer_ward#375]
规则如下：
```id: remote_desktop_protocol
info:
  name: remote_desktop_protocol
  author: nobody
  tags: detect,tech,remote_desktop_protocol
  severity: info
  metadata:
    vender: microsoft
    product:remote_desktop_protocol
    verified: true
tcp:
  - name: remote_desktop_protocol_1
    inputs:
      - data: '\x03\x00\x00\x13\x0e\xe0\x00\x00\x00\x00\x00\x01\x00\x08\x00\x0b\x00\x00\x00'
    host:
      - '{{Hostname}}'
    matchers:
      - type: word
        words:
          - \x03\0\0\x13\x0e\xd0\0\0\x12\x34\0
```
执行命令./observer_ward -t 10.32.0.180:3389 --mode all --silent --format json --probe-dir ./test/ --debug
发现\x3不见了，然后也没能识别出结果

![Image](https://github.com/user-attachments/assets/7ef42b67-554c-4e7d-aecc-0acd37f0896a)

![Image](https://github.com/user-attachments/assets/7601774a-4a9c-4503-a243-e273391f2368)
还有一个问题，匹配器关键词里的\x00一定要写成\0吗，不然好像也不能正确识别。

**Comment by cn-kali-team** [comment]
展示问题，现在都统一改为转义后的了，匹配的也需要在前面加\x
```
[DEBUG] 📤RawRequest {
        uri: tcp://192.168.1.2:3389/,
        raw: \x03\x00\x00\x13\x0e\xe0\x00\x00\x00\x00\x00\x01\x00\x08\x00\x0b\x00\x00\x00,
        unsafe_raw: true,
    }
[DEBUG] 📥Response {
        version: HTTP/1.1,
        uri: /,
        status_code: 200,
        headers: {},
        extensions: Extensions,
        body: Some(
            \x03\x00\x00\x13\x0e\xd0\x00\x00\x124\x00\x02\x0f\x08\x00\x08\x00\x00\x00,
        ),
    }

```
- 模板
```yaml
id: "rdp"
info:
  name: remote_desktop_protocol
  author: nobody
  tags: detect,tech,remote_desktop_protocol
  severity: info
  metadata:
    vender: microsoft
    product: remote_desktop_protocol
    verified: true
tcp:
  - name: remote_desktop_protocol_1
    inputs:
      - data: '\x03\x00\x00\x13\x0e\xe0\x00\x00\x00\x00\x00\x01\x00\x08\x00\x0b\x00\x00\x00'
    host:
      - '{{Hostname}}'
    matchers:
      - type: word
        words:
          - \x03\x00\x00\x13\x0e\xd0\x00\x00

```
- 等ci跑完就可以下载了
https://github.com/emo-crab/observer_ward/actions/runs/13630472144
